### ISSUE TITLE
Meson Install: use less sudo

### ISSUE THREAD

**Issue by themaxw** [tu-studio/osc-kreuz#6]
build dir can only be deleted using sudo, not a fan

**Comment by ntonnaett** [comment]
`meson install` shouldn't change the ownership of any file in the build directory. If it does, it's a bug. `ninja` or `meson -C builddir` shouldn't be run as root.

**Comment by themaxw** [comment]
i think the problem is that we use meson to also install python packages by using `meson.add_install_script`:

``` meson
meson.add_install_script(
	'sh', '-c',
	'sudo @0@/bin/pip install @1@; '.format(
		venv_path, meson.current_source_dir())
)
```
this installs the current directory into a venv in `/usr/local/share`, but the "building" of the python-package happens in a local dir called `build`, which happened to be the same name as my meson builddir.

maybe there is a better way to install python packages with meson (the correct answer is probably "use something else"), or to specify a different buildpath for pip, or to build the package first and then install it using sudo
